# Generated by Django 5.0.9 on 2025-06-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notify_app.notification'),
        ),
    ]
