# Generated by Django 5.0.9 on 2025-06-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'psychology_question_type',
            },
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answers', models.JSONField(null=True)),
                ('scores', models.JSONField(default=list)),
                ('activate', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sets', to='organizers.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sets', to='organizers.partner')),
            ],
            options={
                'db_table': 'psychology_answerset',
            },
        ),
        migrations.CreateModel(
            name='PublishSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(blank=True, default=False)),
                ('survey_details', models.JSONField()),
                ('target', models.JSONField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_surveys', to='organizers.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_surveys', to='organizers.partner')),
            ],
            options={
                'db_table': 'psychology_publish_survey',
            },
        ),
        migrations.CreateModel(
            name='PublishSurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(null=True)),
                ('publish_survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_result', to='psychology_app.publishsurvey')),
            ],
            options={
                'db_table': 'psychology_publish_survey_result',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychology_app.questiontype')),
            ],
            options={
                'db_table': 'psychology_question',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluate', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('answer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='psychology_app.answerset')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='organizers.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='organizers.partner')),
            ],
            options={
                'db_table': 'psychology_survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='psychology_app.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='psychology_app.survey')),
            ],
            options={
                'db_table': 'psychology_survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_types', to='organizers.organization')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_types', to='organizers.partner')),
            ],
            options={
                'db_table': 'psychology_survey_type',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='psychology_app.surveytype'),
        ),
        migrations.CreateModel(
            name='UserPublishSurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(null=True)),
                ('result', models.JSONField(null=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('publish_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_publishsurvey_results', to='psychology_app.publishsurvey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_publishsurvey_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psychology_user_publish_survey_result',
            },
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(fields=('survey', 'question'), name='unique_survey_question'),
        ),
        migrations.AddConstraint(
            model_name='userpublishsurveyresult',
            constraint=models.UniqueConstraint(fields=('user', 'publish_survey'), name='unique_user_publishsurvey'),
        ),
    ]
