# Generated by Django 5.0.9 on 2025-06-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
        ('psychology_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublishsurveyresult',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_publishedsurveys_results', to='organizers.organization'),
        ),
        migrations.AddField(
            model_name='userpublishsurveyresult',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_publishedsurveys_results', to='organizers.partner'),
        ),
    ]
