# Generated by Django 5.0.9 on 2025-06-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_app', '0002_userpublishsurveyresult_organization_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userpublishsurveyresult',
            name='unique_user_publishsurvey',
        ),
    ]
