# Generated by Django 5.0.9 on 2025-05-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_customer_user_is_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organization',
            new_name='is_organizer',
        ),
    ]
