# Generated by Django 5.0.9 on 2025-04-08 09:41

import chatbot_app.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(storage=chatbot_app.utils.CustomStorage(), upload_to='documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=10)),
            ],
            options={
                'db_table': 'chatbot_document',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chatbot_faq',
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_qa_history',
            },
        ),
    ]
