# Generated by Django 5.0.9 on 2025-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qahistory',
            name='intent',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='qahistory',
            name='thread_id',
            field=models.CharField(max_length=36),
        ),
    ]
