# Generated by Django 5.0.9 on 2025-06-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_alter_qahistory_intent_alter_qahistory_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='key',
        ),
    ]
